# Generated by Django 5.2.5 on 2025-09-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0002_rayon'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='rayons',
            field=models.ManyToManyField(related_name='produits', to='monApp.rayon'),
        ),
    ]
