# Generated by Django 5.2.5 on 2025-10-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0002_alter_categorie_nomcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statut',
            name='libelle',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
