# Generated by Django 5.2.5 on 2025-09-16 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0006_produit_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='rayons',
        ),
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('pk', models.CompositePrimaryKey('produit_id', 'rayon_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monApp.produit')),
                ('rayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monApp.rayon')),
            ],
            options={
                'verbose_name': 'Contenir',
                'verbose_name_plural': 'Contenir',
            },
        ),
    ]
